// DeepNode Download Manager — paylaşılan eklenti sözlüğü (TR/EN)
// background.js (importScripts), content.js (manifest js sırasıyla) ve
// popup.html (<script>) tarafından ortak kullanılır.

const DN_STRINGS = {
  en: {
    ctx_download_with: 'Download with DeepNode',
    ctx_download_video: 'Download this video (YouTube etc.)',
    ctx_scan: 'Scan this page for media (Grabber)',
    notif_captured: 'Browser download captured',
    notif_grabber_added: '{n} link(s) added to queue',
    notif_site_disabled: 'DeepNode is disabled on this site',

    btn_download_with: 'Download with DDM',
    btn_hide: 'Hide button',
    btn_aria: 'Download with DeepNode',
    toast_hidden: 'Download button hidden on this page. It will reappear when you navigate.',
    toast_added: 'Added to downloads',
    toast_stream: 'Video stream captured and added',
    toast_blob_fail: 'This video is a live (blob) stream — cannot download directly. Play the video once and try again.',
    toast_video_started: 'Downloading video in the app…',

    q_title: 'Video Quality',
    q_loading: 'Fetching qualities…',
    q_best: 'Best Quality (Auto)',
    q_audio: 'Audio Only (MP3)',
    q_error: 'Could not fetch qualities — "Best" will download the highest resolution.',

    g_download: 'Download',
    g_added: 'Added',
    g_download_all: 'Download all',
    g_all_added: 'All added ({n})',
    g_empty: 'No downloadable media found on this page.',
    g_close: 'Close',

    type_video: 'Video',
    type_audio: 'Audio',
    type_image: 'Image',
    type_document: 'Document',
    type_archive: 'Archive',
    type_program: 'Program',
    type_other: 'Other',

    pop_integration: 'Browser Integration',
    pop_checking: 'Checking the app…',
    pop_connected: 'App connected (localhost:{port})',
    pop_disconnected: 'App not running — open DeepNode Download Manager.',
    pop_update_msg: 'App updated to v{new} — reload the extension to match.',
    pop_reload_btn: 'Reload extension now',
    pop_enabled: 'Integration enabled',
    pop_capture: 'Capture browser downloads',
    pop_show_btn: 'Show Download button on media',
    pop_port: 'App port',
    pop_scan: 'Scan this page for media',
    pop_hint: 'Tip: hover a video/image and a Download button appears in the corner. You can also right-click a link and choose "Download with DeepNode".',
    pop_site_disable: "Don't run on this site",
    pop_site_enable: 'Run on this site',
    pop_site_disabled_note: 'DDM is disabled on {host}'
  },
  tr: {
    ctx_download_with: 'DeepNode ile indir',
    ctx_download_video: 'Bu videoyu indir (YouTube vb.)',
    ctx_scan: 'Bu sayfadaki medyayı tara (Grabber)',
    notif_captured: 'Tarayıcı indirmesi yakalandı',
    notif_grabber_added: '{n} bağlantı kuyruğa eklendi',
    notif_site_disabled: 'Bu sitede DeepNode devre dışı',

    btn_download_with: 'DDM ile İndir',
    btn_hide: 'Butonu gizle',
    btn_aria: 'DeepNode ile indir',
    toast_hidden: 'İndir butonu bu sayfada gizlendi. Başka bir sayfaya geçince tekrar görünür.',
    toast_added: 'İndirmeye eklendi',
    toast_stream: 'Video akışı yakalandı ve eklendi',
    toast_blob_fail: 'Bu video canlı akış (blob) — doğrudan indirilemiyor. Videoyu bir kez oynatıp tekrar dene.',
    toast_video_started: 'Video uygulamada indiriliyor…',

    q_title: 'Görüntü Kalitesi',
    q_loading: 'Kaliteler alınıyor…',
    q_best: 'En Yüksek Kalite (Otomatik)',
    q_audio: 'Sadece Ses (MP3)',
    q_error: 'Kaliteler alınamadı — "En Yüksek" ile en iyi çözünürlük iner.',

    g_download: 'İndir',
    g_added: 'Eklendi',
    g_download_all: 'Tümünü indir',
    g_all_added: 'Tümü eklendi ({n})',
    g_empty: 'Bu sayfada indirilebilir medya bulunamadı.',
    g_close: 'Kapat',

    type_video: 'Video',
    type_audio: 'Ses',
    type_image: 'Resim',
    type_document: 'Belge',
    type_archive: 'Arşiv',
    type_program: 'Program',
    type_other: 'Diğer',

    pop_integration: 'Tarayıcı Entegrasyonu',
    pop_checking: 'Uygulama kontrol ediliyor…',
    pop_connected: 'Uygulama bağlı (localhost:{port})',
    pop_disconnected: 'Uygulama çalışmıyor — DeepNode Download Manager\'ı aç.',
    pop_update_msg: 'Uygulama v{new} sürümüne güncellendi — uzantıyı yenileyerek eşitle.',
    pop_reload_btn: 'Uzantıyı şimdi yenile',
    pop_enabled: 'Entegrasyon açık',
    pop_capture: 'Tarayıcı indirmelerini yakala',
    pop_show_btn: 'Medyada İndir butonu göster',
    pop_port: 'Uygulama portu',
    pop_scan: 'Bu sayfadaki medyayı tara',
    pop_hint: 'İpucu: video/resim üzerine gelince köşede İndir butonu çıkar. Bağlantıya sağ tıklayıp "DeepNode ile indir" de diyebilirsin.',
    pop_site_disable: 'Bu sitede çalışma',
    pop_site_enable: 'Bu sitede çalış',
    pop_site_disabled_note: '{host} sitesinde DDM devre dışı'
  },
  es: {
    ctx_download_with: 'Descargar con DeepNode',
    ctx_download_video: 'Descargar este video (YouTube, etc.)',
    ctx_scan: 'Buscar medios en esta página (Grabber)',
    notif_captured: 'Descarga del navegador capturada',
    notif_grabber_added: '{n} enlace(s) añadidos a la cola',
    notif_site_disabled: 'DeepNode está desactivado en este sitio',

    btn_download_with: 'Descargar con DDM',
    btn_hide: 'Ocultar botón',
    btn_aria: 'Descargar con DeepNode',
    toast_hidden: 'Botón de descarga oculto en esta página. Volverá a aparecer al navegar.',
    toast_added: 'Añadido a las descargas',
    toast_stream: 'Flujo de video capturado y añadido',
    toast_blob_fail: 'Este video es una transmisión en vivo (blob) — no se puede descargar directamente. Reproduce el video una vez e inténtalo de nuevo.',
    toast_video_started: 'Descargando el video en la aplicación…',

    q_title: 'Calidad de video',
    q_loading: 'Obteniendo calidades…',
    q_best: 'Mejor calidad (Auto)',
    q_audio: 'Solo audio (MP3)',
    q_error: 'No se pudieron obtener las calidades — "Mejor" descargará la resolución más alta.',

    g_download: 'Descargar',
    g_added: 'Añadido',
    g_download_all: 'Descargar todo',
    g_all_added: 'Todo añadido ({n})',
    g_empty: 'No se encontraron medios descargables en esta página.',
    g_close: 'Cerrar',

    type_video: 'Video',
    type_audio: 'Audio',
    type_image: 'Imagen',
    type_document: 'Documento',
    type_archive: 'Archivo',
    type_program: 'Programa',
    type_other: 'Otro',

    pop_integration: 'Integración del navegador',
    pop_checking: 'Comprobando la aplicación…',
    pop_connected: 'Aplicación conectada (localhost:{port})',
    pop_disconnected: 'La aplicación no está en ejecución — abre DeepNode Download Manager.',
    pop_update_msg: 'Aplicación actualizada a v{new} — recarga la extensión para sincronizar.',
    pop_reload_btn: 'Recargar extensión ahora',
    pop_enabled: 'Integración activada',
    pop_capture: 'Capturar descargas del navegador',
    pop_show_btn: 'Mostrar botón Descargar en los medios',
    pop_port: 'Puerto de la aplicación',
    pop_scan: 'Buscar medios en esta página',
    pop_hint: 'Consejo: pasa el cursor sobre un video/imagen y aparecerá un botón Descargar en la esquina. También puedes hacer clic derecho en un enlace y elegir "Descargar con DeepNode".',
    pop_site_disable: 'No ejecutar en este sitio',
    pop_site_enable: 'Ejecutar en este sitio',
    pop_site_disabled_note: 'DDM está desactivado en {host}'
  },
  'pt-BR': {
    ctx_download_with: 'Baixar com DeepNode',
    ctx_download_video: 'Baixar este vídeo (YouTube etc.)',
    ctx_scan: 'Procurar mídias nesta página (Grabber)',
    notif_captured: 'Download do navegador capturado',
    notif_grabber_added: '{n} link(s) adicionados à fila',
    notif_site_disabled: 'O DeepNode está desativado neste site',

    btn_download_with: 'Baixar com DDM',
    btn_hide: 'Ocultar botão',
    btn_aria: 'Baixar com DeepNode',
    toast_hidden: 'Botão de download oculto nesta página. Ele reaparecerá quando você navegar.',
    toast_added: 'Adicionado aos downloads',
    toast_stream: 'Fluxo de vídeo capturado e adicionado',
    toast_blob_fail: 'Este vídeo é uma transmissão ao vivo (blob) — não é possível baixar diretamente. Reproduza o vídeo uma vez e tente novamente.',
    toast_video_started: 'Baixando o vídeo no aplicativo…',

    q_title: 'Qualidade do vídeo',
    q_loading: 'Obtendo qualidades…',
    q_best: 'Melhor qualidade (Auto)',
    q_audio: 'Somente áudio (MP3)',
    q_error: 'Não foi possível obter as qualidades — "Melhor" baixará a resolução mais alta.',

    g_download: 'Baixar',
    g_added: 'Adicionado',
    g_download_all: 'Baixar tudo',
    g_all_added: 'Tudo adicionado ({n})',
    g_empty: 'Nenhuma mídia baixável foi encontrada nesta página.',
    g_close: 'Fechar',

    type_video: 'Vídeo',
    type_audio: 'Áudio',
    type_image: 'Imagem',
    type_document: 'Documento',
    type_archive: 'Arquivo',
    type_program: 'Programa',
    type_other: 'Outro',

    pop_integration: 'Integração com o navegador',
    pop_checking: 'Verificando o aplicativo…',
    pop_connected: 'Aplicativo conectado (localhost:{port})',
    pop_disconnected: 'O aplicativo não está em execução — abra o DeepNode Download Manager.',
    pop_update_msg: 'Aplicativo atualizado para v{new} — recarregue a extensão para sincronizar.',
    pop_reload_btn: 'Recarregar extensão agora',
    pop_enabled: 'Integração ativada',
    pop_capture: 'Capturar downloads do navegador',
    pop_show_btn: 'Mostrar botão Baixar nas mídias',
    pop_port: 'Porta do aplicativo',
    pop_scan: 'Procurar mídias nesta página',
    pop_hint: 'Dica: passe o mouse sobre um vídeo/imagem e um botão Baixar aparecerá no canto. Você também pode clicar com o botão direito em um link e escolher "Baixar com DeepNode".',
    pop_site_disable: 'Não executar neste site',
    pop_site_enable: 'Executar neste site',
    pop_site_disabled_note: 'O DDM está desativado em {host}'
  },
  ru: {
    ctx_download_with: 'Скачать через DeepNode',
    ctx_download_video: 'Скачать это видео (YouTube и др.)',
    ctx_scan: 'Найти медиа на этой странице (Grabber)',
    notif_captured: 'Загрузка браузера перехвачена',
    notif_grabber_added: 'Ссылок добавлено в очередь: {n}',
    notif_site_disabled: 'DeepNode отключён на этом сайте',

    btn_download_with: 'Скачать через DDM',
    btn_hide: 'Скрыть кнопку',
    btn_aria: 'Скачать через DeepNode',
    toast_hidden: 'Кнопка загрузки скрыта на этой странице. Она снова появится при переходе.',
    toast_added: 'Добавлено в загрузки',
    toast_stream: 'Видеопоток перехвачен и добавлен',
    toast_blob_fail: 'Это видео — живой поток (blob), его нельзя скачать напрямую. Воспроизведите видео один раз и попробуйте снова.',
    toast_video_started: 'Видео скачивается в приложении…',

    q_title: 'Качество видео',
    q_loading: 'Получение качеств…',
    q_best: 'Лучшее качество (Авто)',
    q_audio: 'Только звук (MP3)',
    q_error: 'Не удалось получить качества — «Лучшее» скачает максимальное разрешение.',

    g_download: 'Скачать',
    g_added: 'Добавлено',
    g_download_all: 'Скачать всё',
    g_all_added: 'Всё добавлено ({n})',
    g_empty: 'На этой странице не найдено медиа для скачивания.',
    g_close: 'Закрыть',

    type_video: 'Видео',
    type_audio: 'Аудио',
    type_image: 'Изображение',
    type_document: 'Документ',
    type_archive: 'Архив',
    type_program: 'Программа',
    type_other: 'Другое',

    pop_integration: 'Интеграция с браузером',
    pop_checking: 'Проверка приложения…',
    pop_connected: 'Приложение подключено (localhost:{port})',
    pop_disconnected: 'Приложение не запущено — откройте DeepNode Download Manager.',
    pop_update_msg: 'Приложение обновлено до v{new} — перезагрузите расширение для синхронизации.',
    pop_reload_btn: 'Перезагрузить расширение',
    pop_enabled: 'Интеграция включена',
    pop_capture: 'Перехватывать загрузки браузера',
    pop_show_btn: 'Показывать кнопку «Скачать» на медиа',
    pop_port: 'Порт приложения',
    pop_scan: 'Найти медиа на этой странице',
    pop_hint: 'Совет: наведите курсор на видео/изображение — в углу появится кнопка «Скачать». Также можно кликнуть по ссылке правой кнопкой и выбрать «Скачать через DeepNode».',
    pop_site_disable: 'Не запускать на этом сайте',
    pop_site_enable: 'Запускать на этом сайте',
    pop_site_disabled_note: 'DDM отключён на {host}'
  },
  de: {
    ctx_download_with: 'Mit DeepNode herunterladen',
    ctx_download_video: 'Dieses Video herunterladen (YouTube usw.)',
    ctx_scan: 'Diese Seite nach Medien durchsuchen (Grabber)',
    notif_captured: 'Browser-Download abgefangen',
    notif_grabber_added: '{n} Link(s) zur Warteschlange hinzugefügt',
    notif_site_disabled: 'DeepNode ist auf dieser Seite deaktiviert',

    btn_download_with: 'Mit DDM herunterladen',
    btn_hide: 'Button ausblenden',
    btn_aria: 'Mit DeepNode herunterladen',
    toast_hidden: 'Download-Button auf dieser Seite ausgeblendet. Er erscheint beim Navigieren wieder.',
    toast_added: 'Zu Downloads hinzugefügt',
    toast_stream: 'Videostream erfasst und hinzugefügt',
    toast_blob_fail: 'Dieses Video ist ein Live-Stream (blob) — direkter Download nicht möglich. Video einmal abspielen und erneut versuchen.',
    toast_video_started: 'Video wird in der App heruntergeladen…',

    q_title: 'Videoqualität',
    q_loading: 'Qualitäten werden abgerufen…',
    q_best: 'Beste Qualität (Auto)',
    q_audio: 'Nur Audio (MP3)',
    q_error: 'Qualitäten konnten nicht abgerufen werden — „Beste“ lädt die höchste Auflösung herunter.',

    g_download: 'Herunterladen',
    g_added: 'Hinzugefügt',
    g_download_all: 'Alle herunterladen',
    g_all_added: 'Alle hinzugefügt ({n})',
    g_empty: 'Auf dieser Seite wurden keine herunterladbaren Medien gefunden.',
    g_close: 'Schließen',

    type_video: 'Video',
    type_audio: 'Audio',
    type_image: 'Bild',
    type_document: 'Dokument',
    type_archive: 'Archiv',
    type_program: 'Programm',
    type_other: 'Sonstiges',

    pop_integration: 'Browser-Integration',
    pop_checking: 'App wird geprüft…',
    pop_connected: 'App verbunden (localhost:{port})',
    pop_disconnected: 'App läuft nicht — öffne den DeepNode Download Manager.',
    pop_update_msg: 'App auf v{new} aktualisiert — Erweiterung neu laden, um zu synchronisieren.',
    pop_reload_btn: 'Erweiterung jetzt neu laden',
    pop_enabled: 'Integration aktiviert',
    pop_capture: 'Browser-Downloads abfangen',
    pop_show_btn: 'Download-Button auf Medien anzeigen',
    pop_port: 'App-Port',
    pop_scan: 'Diese Seite nach Medien durchsuchen',
    pop_hint: 'Tipp: Bewege den Mauszeiger über ein Video/Bild — in der Ecke erscheint ein Download-Button. Du kannst auch mit Rechtsklick auf einen Link „Mit DeepNode herunterladen" wählen.',
    pop_site_disable: 'Auf dieser Seite nicht ausführen',
    pop_site_enable: 'Auf dieser Seite ausführen',
    pop_site_disabled_note: 'DDM ist auf {host} deaktiviert'
  },
  fr: {
    ctx_download_with: 'Télécharger avec DeepNode',
    ctx_download_video: 'Télécharger cette vidéo (YouTube, etc.)',
    ctx_scan: 'Rechercher des médias sur cette page (Grabber)',
    notif_captured: 'Téléchargement du navigateur capturé',
    notif_grabber_added: '{n} lien(s) ajoutés à la file',
    notif_site_disabled: 'DeepNode est désactivé sur ce site',

    btn_download_with: 'Télécharger avec DDM',
    btn_hide: 'Masquer le bouton',
    btn_aria: 'Télécharger avec DeepNode',
    toast_hidden: 'Bouton de téléchargement masqué sur cette page. Il réapparaîtra lors de la navigation.',
    toast_added: 'Ajouté aux téléchargements',
    toast_stream: 'Flux vidéo capturé et ajouté',
    toast_blob_fail: 'Cette vidéo est un flux en direct (blob) — téléchargement direct impossible. Lisez la vidéo une fois puis réessayez.',
    toast_video_started: 'Téléchargement de la vidéo dans l\'application…',

    q_title: 'Qualité vidéo',
    q_loading: 'Récupération des qualités…',
    q_best: 'Meilleure qualité (Auto)',
    q_audio: 'Audio uniquement (MP3)',
    q_error: 'Impossible de récupérer les qualités — « Meilleure » téléchargera la plus haute résolution.',

    g_download: 'Télécharger',
    g_added: 'Ajouté',
    g_download_all: 'Tout télécharger',
    g_all_added: 'Tout ajouté ({n})',
    g_empty: 'Aucun média téléchargeable trouvé sur cette page.',
    g_close: 'Fermer',

    type_video: 'Vidéo',
    type_audio: 'Audio',
    type_image: 'Image',
    type_document: 'Document',
    type_archive: 'Archive',
    type_program: 'Programme',
    type_other: 'Autre',

    pop_integration: 'Intégration du navigateur',
    pop_checking: 'Vérification de l\'application…',
    pop_connected: 'Application connectée (localhost:{port})',
    pop_disconnected: 'L\'application n\'est pas lancée — ouvrez DeepNode Download Manager.',
    pop_update_msg: 'Application mise à jour en v{new} — rechargez l\'extension pour synchroniser.',
    pop_reload_btn: 'Recharger l\'extension maintenant',
    pop_enabled: 'Intégration activée',
    pop_capture: 'Capturer les téléchargements du navigateur',
    pop_show_btn: 'Afficher le bouton Télécharger sur les médias',
    pop_port: 'Port de l\'application',
    pop_scan: 'Rechercher des médias sur cette page',
    pop_hint: 'Astuce : survolez une vidéo/image et un bouton Télécharger apparaît dans le coin. Vous pouvez aussi faire un clic droit sur un lien et choisir « Télécharger avec DeepNode ».',
    pop_site_disable: 'Ne pas exécuter sur ce site',
    pop_site_enable: 'Exécuter sur ce site',
    pop_site_disabled_note: 'DDM est désactivé sur {host}'
  },
  'zh-CN': {
    ctx_download_with: '使用 DeepNode 下载',
    ctx_download_video: '下载此视频（YouTube 等）',
    ctx_scan: '扫描此页面中的媒体（抓取器）',
    notif_captured: '已捕获浏览器下载',
    notif_grabber_added: '已将 {n} 个链接加入队列',
    notif_site_disabled: 'DeepNode 已在此网站禁用',

    btn_download_with: '用 DDM 下载',
    btn_hide: '隐藏按钮',
    btn_aria: '使用 DeepNode 下载',
    toast_hidden: '已在此页面隐藏下载按钮，切换页面后会重新显示。',
    toast_added: '已加入下载',
    toast_stream: '已捕获并添加视频流',
    toast_blob_fail: '此视频是实时流（blob），无法直接下载。请先播放一次视频后重试。',
    toast_video_started: '正在应用中下载视频…',

    q_title: '视频画质',
    q_loading: '正在获取画质…',
    q_best: '最佳画质（自动）',
    q_audio: '仅音频（MP3）',
    q_error: '无法获取画质 — 选择“最佳”将下载最高分辨率。',

    g_download: '下载',
    g_added: '已添加',
    g_download_all: '全部下载',
    g_all_added: '已全部添加（{n}）',
    g_empty: '此页面未找到可下载的媒体。',
    g_close: '关闭',

    type_video: '视频',
    type_audio: '音频',
    type_image: '图片',
    type_document: '文档',
    type_archive: '压缩包',
    type_program: '程序',
    type_other: '其他',

    pop_integration: '浏览器集成',
    pop_checking: '正在检查应用…',
    pop_connected: '应用已连接（localhost:{port}）',
    pop_disconnected: '应用未运行 — 请打开 DeepNode Download Manager。',
    pop_update_msg: '应用已更新到 v{new} — 请重新加载扩展以同步。',
    pop_reload_btn: '立即重新加载扩展',
    pop_enabled: '已启用集成',
    pop_capture: '捕获浏览器下载',
    pop_show_btn: '在媒体上显示下载按钮',
    pop_port: '应用端口',
    pop_scan: '扫描此页面中的媒体',
    pop_hint: '提示：将鼠标悬停在视频/图片上，角落会出现下载按钮。也可以右键点击链接并选择“使用 DeepNode 下载”。',
    pop_site_disable: '不在此网站运行',
    pop_site_enable: '在此网站运行',
    pop_site_disabled_note: 'DDM 已在 {host} 禁用'
  },
  ar: {
    ctx_download_with: 'التنزيل باستخدام DeepNode',
    ctx_download_video: 'تنزيل هذا الفيديو (YouTube وغيره)',
    ctx_scan: 'فحص هذه الصفحة بحثًا عن الوسائط (Grabber)',
    notif_captured: 'تم التقاط تنزيل المتصفح',
    notif_grabber_added: 'تمت إضافة {n} رابط/روابط إلى قائمة الانتظار',
    notif_site_disabled: 'DeepNode معطّل على هذا الموقع',

    btn_download_with: 'تنزيل عبر DDM',
    btn_hide: 'إخفاء الزر',
    btn_aria: 'التنزيل باستخدام DeepNode',
    toast_hidden: 'تم إخفاء زر التنزيل في هذه الصفحة. سيظهر مجددًا عند التنقل.',
    toast_added: 'تمت الإضافة إلى التنزيلات',
    toast_stream: 'تم التقاط بث الفيديو وإضافته',
    toast_blob_fail: 'هذا الفيديو بث مباشر (blob) — لا يمكن تنزيله مباشرة. شغّل الفيديو مرة واحدة ثم حاول مجددًا.',
    toast_video_started: 'جارٍ تنزيل الفيديو في التطبيق…',

    q_title: 'جودة الفيديو',
    q_loading: 'جارٍ جلب الجودات…',
    q_best: 'أفضل جودة (تلقائي)',
    q_audio: 'الصوت فقط (MP3)',
    q_error: 'تعذّر جلب الجودات — خيار "الأفضل" سينزّل أعلى دقة.',

    g_download: 'تنزيل',
    g_added: 'تمت الإضافة',
    g_download_all: 'تنزيل الكل',
    g_all_added: 'تمت إضافة الكل ({n})',
    g_empty: 'لم يتم العثور على وسائط قابلة للتنزيل في هذه الصفحة.',
    g_close: 'إغلاق',

    type_video: 'فيديو',
    type_audio: 'صوت',
    type_image: 'صورة',
    type_document: 'مستند',
    type_archive: 'أرشيف',
    type_program: 'برنامج',
    type_other: 'أخرى',

    pop_integration: 'تكامل المتصفح',
    pop_checking: 'جارٍ التحقق من التطبيق…',
    pop_connected: 'التطبيق متصل (localhost:{port})',
    pop_disconnected: 'التطبيق غير مشغّل — افتح DeepNode Download Manager.',
    pop_update_msg: 'تم تحديث التطبيق إلى الإصدار v{new} — أعد تحميل الإضافة للمزامنة.',
    pop_reload_btn: 'إعادة تحميل الإضافة الآن',
    pop_enabled: 'التكامل مفعّل',
    pop_capture: 'التقاط تنزيلات المتصفح',
    pop_show_btn: 'إظهار زر التنزيل على الوسائط',
    pop_port: 'منفذ التطبيق',
    pop_scan: 'فحص هذه الصفحة بحثًا عن الوسائط',
    pop_hint: 'تلميح: مرّر المؤشر فوق فيديو/صورة وسيظهر زر تنزيل في الزاوية. يمكنك أيضًا النقر بزر الفأرة الأيمن على رابط واختيار "التنزيل باستخدام DeepNode".',
    pop_site_disable: 'عدم التشغيل على هذا الموقع',
    pop_site_enable: 'التشغيل على هذا الموقع',
    pop_site_disabled_note: 'DDM معطّل على {host}'
  },
  hi: {
    ctx_download_with: 'DeepNode से डाउनलोड करें',
    ctx_download_video: 'यह वीडियो डाउनलोड करें (YouTube आदि)',
    ctx_scan: 'इस पेज पर मीडिया खोजें (Grabber)',
    notif_captured: 'ब्राउज़र डाउनलोड पकड़ा गया',
    notif_grabber_added: '{n} लिंक कतार में जोड़े गए',
    notif_site_disabled: 'इस साइट पर DeepNode अक्षम है',

    btn_download_with: 'DDM से डाउनलोड करें',
    btn_hide: 'बटन छिपाएँ',
    btn_aria: 'DeepNode से डाउनलोड करें',
    toast_hidden: 'इस पेज पर डाउनलोड बटन छिपा दिया गया। नेविगेट करने पर यह फिर दिखेगा।',
    toast_added: 'डाउनलोड में जोड़ा गया',
    toast_stream: 'वीडियो स्ट्रीम पकड़ी गई और जोड़ी गई',
    toast_blob_fail: 'यह वीडियो लाइव (blob) स्ट्रीम है — सीधे डाउनलोड नहीं हो सकता। वीडियो एक बार चलाकर फिर कोशिश करें।',
    toast_video_started: 'ऐप में वीडियो डाउनलोड हो रहा है…',

    q_title: 'वीडियो गुणवत्ता',
    q_loading: 'गुणवत्ताएँ लाई जा रही हैं…',
    q_best: 'सर्वश्रेष्ठ गुणवत्ता (स्वतः)',
    q_audio: 'केवल ऑडियो (MP3)',
    q_error: 'गुणवत्ताएँ नहीं मिलीं — "सर्वश्रेष्ठ" से उच्चतम रिज़ॉल्यूशन डाउनलोड होगा।',

    g_download: 'डाउनलोड',
    g_added: 'जोड़ा गया',
    g_download_all: 'सभी डाउनलोड करें',
    g_all_added: 'सभी जोड़े गए ({n})',
    g_empty: 'इस पेज पर डाउनलोड करने योग्य मीडिया नहीं मिला।',
    g_close: 'बंद करें',

    type_video: 'वीडियो',
    type_audio: 'ऑडियो',
    type_image: 'छवि',
    type_document: 'दस्तावेज़',
    type_archive: 'आर्काइव',
    type_program: 'प्रोग्राम',
    type_other: 'अन्य',

    pop_integration: 'ब्राउज़र एकीकरण',
    pop_checking: 'ऐप की जाँच हो रही है…',
    pop_connected: 'ऐप कनेक्टेड है (localhost:{port})',
    pop_disconnected: 'ऐप नहीं चल रहा — DeepNode Download Manager खोलें।',
    pop_update_msg: 'ऐप v{new} में अपडेट हुआ — मिलान के लिए एक्सटेंशन फिर लोड करें।',
    pop_reload_btn: 'एक्सटेंशन अभी फिर लोड करें',
    pop_enabled: 'एकीकरण चालू',
    pop_capture: 'ब्राउज़र डाउनलोड पकड़ें',
    pop_show_btn: 'मीडिया पर डाउनलोड बटन दिखाएँ',
    pop_port: 'ऐप पोर्ट',
    pop_scan: 'इस पेज पर मीडिया खोजें',
    pop_hint: 'सुझाव: वीडियो/छवि पर कर्सर ले जाएँ तो कोने में डाउनलोड बटन दिखेगा। लिंक पर राइट-क्लिक कर "DeepNode से डाउनलोड करें" भी चुन सकते हैं।',
    pop_site_disable: 'इस साइट पर न चलाएँ',
    pop_site_enable: 'इस साइट पर चलाएँ',
    pop_site_disabled_note: '{host} पर DDM अक्षम है'
  },
  id: {
    ctx_download_with: 'Unduh dengan DeepNode',
    ctx_download_video: 'Unduh video ini (YouTube dll.)',
    ctx_scan: 'Pindai media di halaman ini (Grabber)',
    notif_captured: 'Unduhan browser tertangkap',
    notif_grabber_added: '{n} tautan ditambahkan ke antrean',
    notif_site_disabled: 'DeepNode dinonaktifkan di situs ini',

    btn_download_with: 'Unduh dengan DDM',
    btn_hide: 'Sembunyikan tombol',
    btn_aria: 'Unduh dengan DeepNode',
    toast_hidden: 'Tombol unduh disembunyikan di halaman ini. Akan muncul lagi saat berpindah halaman.',
    toast_added: 'Ditambahkan ke unduhan',
    toast_stream: 'Stream video tertangkap dan ditambahkan',
    toast_blob_fail: 'Video ini adalah stream langsung (blob) — tidak bisa diunduh langsung. Putar video sekali lalu coba lagi.',
    toast_video_started: 'Mengunduh video di aplikasi…',

    q_title: 'Kualitas Video',
    q_loading: 'Mengambil kualitas…',
    q_best: 'Kualitas Terbaik (Otomatis)',
    q_audio: 'Hanya Audio (MP3)',
    q_error: 'Gagal mengambil kualitas — "Terbaik" akan mengunduh resolusi tertinggi.',

    g_download: 'Unduh',
    g_added: 'Ditambahkan',
    g_download_all: 'Unduh semua',
    g_all_added: 'Semua ditambahkan ({n})',
    g_empty: 'Tidak ada media yang dapat diunduh di halaman ini.',
    g_close: 'Tutup',

    type_video: 'Video',
    type_audio: 'Audio',
    type_image: 'Gambar',
    type_document: 'Dokumen',
    type_archive: 'Arsip',
    type_program: 'Program',
    type_other: 'Lainnya',

    pop_integration: 'Integrasi Browser',
    pop_checking: 'Memeriksa aplikasi…',
    pop_connected: 'Aplikasi terhubung (localhost:{port})',
    pop_disconnected: 'Aplikasi tidak berjalan — buka DeepNode Download Manager.',
    pop_update_msg: 'Aplikasi diperbarui ke v{new} — muat ulang ekstensi untuk menyinkronkan.',
    pop_reload_btn: 'Muat ulang ekstensi sekarang',
    pop_enabled: 'Integrasi aktif',
    pop_capture: 'Tangkap unduhan browser',
    pop_show_btn: 'Tampilkan tombol Unduh pada media',
    pop_port: 'Port aplikasi',
    pop_scan: 'Pindai media di halaman ini',
    pop_hint: 'Tips: arahkan kursor ke video/gambar dan tombol Unduh muncul di sudut. Kamu juga bisa klik kanan tautan lalu pilih "Unduh dengan DeepNode".',
    pop_site_disable: 'Jangan jalankan di situs ini',
    pop_site_enable: 'Jalankan di situs ini',
    pop_site_disabled_note: 'DDM dinonaktifkan di {host}'
  },
  vi: {
    ctx_download_with: 'Tải xuống bằng DeepNode',
    ctx_download_video: 'Tải video này (YouTube v.v.)',
    ctx_scan: 'Quét media trên trang này (Grabber)',
    notif_captured: 'Đã bắt lượt tải xuống của trình duyệt',
    notif_grabber_added: 'Đã thêm {n} liên kết vào hàng đợi',
    notif_site_disabled: 'DeepNode bị tắt trên trang web này',

    btn_download_with: 'Tải bằng DDM',
    btn_hide: 'Ẩn nút',
    btn_aria: 'Tải xuống bằng DeepNode',
    toast_hidden: 'Đã ẩn nút tải xuống trên trang này. Nút sẽ xuất hiện lại khi bạn chuyển trang.',
    toast_added: 'Đã thêm vào danh sách tải',
    toast_stream: 'Đã bắt và thêm luồng video',
    toast_blob_fail: 'Video này là luồng trực tiếp (blob) — không thể tải trực tiếp. Phát video một lần rồi thử lại.',
    toast_video_started: 'Đang tải video trong ứng dụng…',

    q_title: 'Chất lượng video',
    q_loading: 'Đang lấy danh sách chất lượng…',
    q_best: 'Chất lượng tốt nhất (Tự động)',
    q_audio: 'Chỉ âm thanh (MP3)',
    q_error: 'Không lấy được chất lượng — "Tốt nhất" sẽ tải độ phân giải cao nhất.',

    g_download: 'Tải xuống',
    g_added: 'Đã thêm',
    g_download_all: 'Tải tất cả',
    g_all_added: 'Đã thêm tất cả ({n})',
    g_empty: 'Không tìm thấy media có thể tải trên trang này.',
    g_close: 'Đóng',

    type_video: 'Video',
    type_audio: 'Âm thanh',
    type_image: 'Hình ảnh',
    type_document: 'Tài liệu',
    type_archive: 'Tệp nén',
    type_program: 'Chương trình',
    type_other: 'Khác',

    pop_integration: 'Tích hợp trình duyệt',
    pop_checking: 'Đang kiểm tra ứng dụng…',
    pop_connected: 'Ứng dụng đã kết nối (localhost:{port})',
    pop_disconnected: 'Ứng dụng chưa chạy — hãy mở DeepNode Download Manager.',
    pop_update_msg: 'Ứng dụng đã cập nhật lên v{new} — tải lại tiện ích để đồng bộ.',
    pop_reload_btn: 'Tải lại tiện ích ngay',
    pop_enabled: 'Đã bật tích hợp',
    pop_capture: 'Bắt lượt tải xuống của trình duyệt',
    pop_show_btn: 'Hiện nút Tải xuống trên media',
    pop_port: 'Cổng ứng dụng',
    pop_scan: 'Quét media trên trang này',
    pop_hint: 'Mẹo: di chuột lên video/hình ảnh, nút Tải xuống sẽ hiện ở góc. Bạn cũng có thể nhấp chuột phải vào liên kết và chọn "Tải xuống bằng DeepNode".',
    pop_site_disable: 'Không chạy trên trang này',
    pop_site_enable: 'Chạy trên trang này',
    pop_site_disabled_note: 'DDM bị tắt trên {host}'
  },
  ja: {
    ctx_download_with: 'DeepNode でダウンロード',
    ctx_download_video: 'この動画をダウンロード（YouTube など）',
    ctx_scan: 'このページのメディアをスキャン（Grabber）',
    notif_captured: 'ブラウザのダウンロードをキャッチしました',
    notif_grabber_added: '{n} 件のリンクをキューに追加しました',
    notif_site_disabled: 'このサイトでは DeepNode が無効です',

    btn_download_with: 'DDM でダウンロード',
    btn_hide: 'ボタンを隠す',
    btn_aria: 'DeepNode でダウンロード',
    toast_hidden: 'このページではダウンロードボタンを非表示にしました。ページ移動で再表示されます。',
    toast_added: 'ダウンロードに追加しました',
    toast_stream: '動画ストリームをキャッチして追加しました',
    toast_blob_fail: 'この動画はライブ（blob）ストリームのため直接ダウンロードできません。動画を一度再生してから再試行してください。',
    toast_video_started: 'アプリで動画をダウンロード中…',

    q_title: '動画の画質',
    q_loading: '画質を取得中…',
    q_best: '最高画質（自動）',
    q_audio: '音声のみ（MP3）',
    q_error: '画質を取得できませんでした — 「最高」を選ぶと最高解像度でダウンロードします。',

    g_download: 'ダウンロード',
    g_added: '追加済み',
    g_download_all: 'すべてダウンロード',
    g_all_added: 'すべて追加しました（{n}）',
    g_empty: 'このページにダウンロード可能なメディアは見つかりませんでした。',
    g_close: '閉じる',

    type_video: '動画',
    type_audio: '音声',
    type_image: '画像',
    type_document: 'ドキュメント',
    type_archive: 'アーカイブ',
    type_program: 'プログラム',
    type_other: 'その他',

    pop_integration: 'ブラウザ連携',
    pop_checking: 'アプリを確認中…',
    pop_connected: 'アプリ接続済み（localhost:{port}）',
    pop_disconnected: 'アプリが起動していません — DeepNode Download Manager を開いてください。',
    pop_update_msg: 'アプリが v{new} に更新されました — 拡張機能を再読み込みして同期してください。',
    pop_reload_btn: '今すぐ拡張機能を再読み込み',
    pop_enabled: '連携オン',
    pop_capture: 'ブラウザのダウンロードをキャッチ',
    pop_show_btn: 'メディアにダウンロードボタンを表示',
    pop_port: 'アプリのポート',
    pop_scan: 'このページのメディアをスキャン',
    pop_hint: 'ヒント：動画/画像にカーソルを合わせると、隅にダウンロードボタンが表示されます。リンクを右クリックして「DeepNode でダウンロード」を選ぶこともできます。',
    pop_site_disable: 'このサイトでは実行しない',
    pop_site_enable: 'このサイトで実行する',
    pop_site_disabled_note: '{host} では DDM が無効です'
  },
  ko: {
    ctx_download_with: 'DeepNode로 다운로드',
    ctx_download_video: '이 동영상 다운로드 (YouTube 등)',
    ctx_scan: '이 페이지에서 미디어 검색 (Grabber)',
    notif_captured: '브라우저 다운로드를 가로챘습니다',
    notif_grabber_added: '링크 {n}개를 대기열에 추가했습니다',
    notif_site_disabled: '이 사이트에서 DeepNode가 비활성화되어 있습니다',

    btn_download_with: 'DDM으로 다운로드',
    btn_hide: '버튼 숨기기',
    btn_aria: 'DeepNode로 다운로드',
    toast_hidden: '이 페이지에서 다운로드 버튼을 숨겼습니다. 페이지를 이동하면 다시 표시됩니다.',
    toast_added: '다운로드에 추가됨',
    toast_stream: '동영상 스트림을 가로채 추가했습니다',
    toast_blob_fail: '이 동영상은 라이브(blob) 스트림이라 직접 다운로드할 수 없습니다. 동영상을 한 번 재생한 뒤 다시 시도하세요.',
    toast_video_started: '앱에서 동영상 다운로드 중…',

    q_title: '동영상 화질',
    q_loading: '화질 목록 가져오는 중…',
    q_best: '최고 화질 (자동)',
    q_audio: '오디오만 (MP3)',
    q_error: '화질 목록을 가져오지 못했습니다 — "최고"를 선택하면 최고 해상도로 다운로드합니다.',

    g_download: '다운로드',
    g_added: '추가됨',
    g_download_all: '모두 다운로드',
    g_all_added: '모두 추가됨 ({n})',
    g_empty: '이 페이지에서 다운로드 가능한 미디어를 찾지 못했습니다.',
    g_close: '닫기',

    type_video: '동영상',
    type_audio: '오디오',
    type_image: '이미지',
    type_document: '문서',
    type_archive: '압축 파일',
    type_program: '프로그램',
    type_other: '기타',

    pop_integration: '브라우저 통합',
    pop_checking: '앱 확인 중…',
    pop_connected: '앱 연결됨 (localhost:{port})',
    pop_disconnected: '앱이 실행 중이 아닙니다 — DeepNode Download Manager를 여세요.',
    pop_update_msg: '앱이 v{new}(으)로 업데이트되었습니다 — 확장 프로그램을 새로고침해 동기화하세요.',
    pop_reload_btn: '지금 확장 프로그램 새로고침',
    pop_enabled: '통합 사용 중',
    pop_capture: '브라우저 다운로드 가로채기',
    pop_show_btn: '미디어에 다운로드 버튼 표시',
    pop_port: '앱 포트',
    pop_scan: '이 페이지에서 미디어 검색',
    pop_hint: '팁: 동영상/이미지에 마우스를 올리면 모서리에 다운로드 버튼이 나타납니다. 링크를 우클릭해 "DeepNode로 다운로드"를 선택할 수도 있습니다.',
    pop_site_disable: '이 사이트에서 실행 안 함',
    pop_site_enable: '이 사이트에서 실행',
    pop_site_disabled_note: '{host}에서 DDM이 비활성화됨'
  }
};

// Dil çözümleme: uygulama ayarı (appLang: 'auto'|desteklenen kod) öncelikli;
// 'auto' ise tarayıcı arayüz dili (tam eşleşme → taban dil → taban eşlemesi → en).
const DN_SUPPORTED = Object.keys(DN_STRINGS);
const DN_BASE_MAP = { pt: 'pt-BR', zh: 'zh-CN' };

function dnResolveLang(appLang, uiLang) {
  if (DN_SUPPORTED.includes(appLang)) return appLang;
  const loc = String(uiLang || 'en');
  const exact = DN_SUPPORTED.find((l) => l.toLowerCase() === loc.toLowerCase());
  if (exact) return exact;
  const base = loc.toLowerCase().split('-')[0];
  if (DN_SUPPORTED.includes(base)) return base;
  if (DN_BASE_MAP[base]) return DN_BASE_MAP[base];
  return 'en';
}

const DN_I18N = {
  lang: 'en',
  t(key, vars) {
    const dict = DN_STRINGS[this.lang] || DN_STRINGS.en;
    let s = dict[key];
    if (s === undefined) s = DN_STRINGS.en[key];
    if (s === undefined) return key;
    if (vars) {
      for (const k of Object.keys(vars)) {
        s = s.split('{' + k + '}').join(String(vars[k]));
      }
    }
    return s;
  },
  setLang(lang) {
    this.lang = DN_SUPPORTED.includes(lang) ? lang : 'en';
  }
};

// Site engelleme yardımcıları: disabledSites dizisi hostname barındırır;
// 'example.com' girdisi 'www.example.com' ve tüm alt alan adlarını kapsar.
function dnHostMatches(host, site) {
  if (!host || !site) return false;
  host = host.toLowerCase();
  site = site.toLowerCase();
  return host === site || host.endsWith('.' + site);
}

function dnIsSiteBlocked(host, disabledSites) {
  if (!host || !Array.isArray(disabledSites)) return false;
  return disabledSites.some((s) => dnHostMatches(host, s));
}
